### ISSUE TITLE
pyLipd integration into tutorials

### ISSUE THREAD

**Issue by CommonClimate** [LinkedEarth/PyleoTutorials#23]
`L1_working_with_LiPD.ipynb` should be updated to reflect pyLipd updates, when the latter are ready for prime time. 

Note: Euro2k example can go either there or in the MSES tutorial

**Comment by khider** [comment]
Going from LiPD to Series/GeoSeries/MulitpleGeoSeries. Need to move the functions supported by LiPD/LiPD Series to the classes:

- LiPD: 

- [ ] to_tso: No longer needed since we do not deal exclusively with LiPD
- [ ] to_LipdSeries: Creates a LiPDSeries from the object. An equivalent function would be MultipleSeries -> Series
- [ ] to_LipdSeriesList: Extracted all available series to create a MultipleSeries object. No longer needed
- [ ] extract: This was mostly internal and allowed to get the information contain at the LiPD level (ensembles) to the timeseries level (variables)
- [ ] mapAllArchive : Maps per archive. The underlying function takes a criteria parameter (i.e., archive) but would leave the work to find the values to a user. With MultipleGeoSeries, we could create a parameter that makes this map by archive or elevation...

- LiPDSeries:

- [ ] chronEnsembletoPaleo: Should be independent function that would also allow to take Series and tables from other file format
- [ ] map : Creates a map - Now should be in GeoSeries
- [ ] getMetadata: Internal function to get relevant metadata for the dashboard. Would need full LiPD information
- [ ] dashboard: Can be attached to GeoSeries if we remove metadata dependency. The question is how to do the ensemble version - create a dashboard function for EnsembleGeoSeries
- [ ] mapNearRecord: Would need a complimentary MultipleGeoSeries object to work
- [ ] plot_age_depth : Remove from Pyleoclim
